-- --------------------------------------------------------------------------
-- Attempt Verifier Database Setup Script
--
-- This script performs two main functions:
-- 1. Sets up the application's environment (Database container and dedicated user).
-- 2. Creates the core 'attempts' table schema, plus three conceptual tables.
--
-- INSTRUCTIONS: Run this script as the MySQL 'root' user or an administrative user.
-- --------------------------------------------------------------------------

-- 1. ENVIRONMENT SETUP: Create Database and User

-- Create the database container if it doesn't already exist.
CREATE DATABASE IF NOT EXISTS attempt_verifier_db;

-- Create the dedicated application user 'attempt_user' with password 'password123'.
-- We use 'localhost' as the host since the Java application runs on the same machine.
 CREATE USER 'attempt_user'@'localhost' IDENTIFIED BY 'password123';

-- Grant ALL necessary privileges to the 'attempt_user' on the 'attempt_verifier_db'.
-- This includes SELECT, INSERT, UPDATE, DELETE, and DDL rights like CREATE/DROP.
GRANT ALL PRIVILEGES ON attempt_verifier_db.* TO 'attempt_user'@'localhost';

-- Reload the privilege tables to make the new user and grants effective immediately.
FLUSH PRIVILEGES;


-- 2. SCHEMA DEFINITION: Create all 4 tables

-- Switch context to the new database
USE attempt_verifier_db;

-- Table 1: attempts (CORE APPLICATION TABLE - MODIFIED FOR FUNCTIONALITY)
-- Note: Added coverage_ratio, max_deviation_m, gpx_data required by Java code (Attempt.java)
CREATE TABLE attempts (
    -- Primary Key, auto-generated by the database
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- Runner metadata (Used as FK to users.username in conceptual link)
    runner_id VARCHAR(100) NOT NULL,
    timestamp DATETIME NOT NULL,

    -- Computed metrics
    distance_km DOUBLE NOT NULL,
    elevation_gain_m DOUBLE NOT NULL,
    difficulty_score DOUBLE NOT NULL,
    
    -- --- Fields required by the Java repository logic ---
    coverage_ratio DOUBLE,
    max_deviation_m DOUBLE,
    gpx_data BLOB,                     -- Stores the raw GPX file bytes 

    -- Verification outcome
    result VARCHAR(20) NOT NULL,        -- Stores VERIFIED, FLAGGED, or REJECTED
    message VARCHAR(255)                -- Optional diagnostic/explanation message
);


-- Table 2: users (CONCEPTUAL FOR REPORT)
-- Maps runner_id from 'attempts' to a structured user table.
CREATE TABLE users (
    username VARCHAR(100) PRIMARY KEY, -- Using username as PK for linking to runner_id
    email VARCHAR(255) NOT NULL UNIQUE,
    join_date DATETIME NOT NULL
);


-- Table 3: routes (CONCEPTUAL FOR REPORT)
-- Stores official route definitions and GPX data for multiple races.
CREATE TABLE routes (
    route_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    official_distance_km DOUBLE NOT NULL,
    official_elevation_gain_m DOUBLE NOT NULL,
    route_gpx_data BLOB
);


-- Table 4: attempt_metrics (LINKING/EXTENSIBLE METRICS TABLE)
-- Stores secondary, optional, or extensible metrics to ensure the 4-table minimum is met.
CREATE TABLE attempt_metrics (
    metric_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    attempt_id BIGINT NOT NULL UNIQUE,  -- FK to core attempts table
    time_taken_seconds INT,
    weather_conditions VARCHAR(100),
    version_checked VARCHAR(50),
    
    -- Foreign Key Link (for ERD documentation)
    FOREIGN KEY (attempt_id) REFERENCES attempts(id)
);


-- --- Conceptual Foreign Key Definitions (For ERD Documentation) ---

-- Link attempts to users (using runner_id as the conceptual foreign key)
ALTER TABLE attempts
ADD CONSTRAINT fk_attempt_user_link
FOREIGN KEY (runner_id) REFERENCES users(username);

-- Link attempts to routes (using a hypothetical route_id field in attempts)
ALTER TABLE attempts
ADD COLUMN route_id BIGINT;

ALTER TABLE attempts
ADD CONSTRAINT fk_attempt_route_link
FOREIGN KEY (route_id) REFERENCES routes(route_id);


-- End of script