-- --------------------------------------------------------------------------
-- Attempt Verifier Database Setup Script
--
-- This script performs two main functions:
-- 1. Sets up the application's environment (Database container and dedicated user).
-- 2. Creates the core 'attempts' table schema.
--
-- INSTRUCTIONS: Run this script as the MySQL 'root' user or an administrative user.
-- --------------------------------------------------------------------------

-- 1. ENVIRONMENT SETUP: Create Database and User

-- Create the database container if it doesn't already exist.
CREATE DATABASE IF NOT EXISTS attempt_verifier_db;

-- Create the dedicated application user 'attempt_user' with password 'password123'.
-- We use 'localhost' as the host since the Java application runs on the same machine.
CREATE USER 'attempt_user'@'localhost' IDENTIFIED BY 'password123';

-- Grant ALL necessary privileges to the 'attempt_user' on the 'attempt_verifier_db'.
-- This includes SELECT, INSERT, UPDATE, DELETE, and DDL rights like CREATE/DROP.
GRANT ALL PRIVILEGES ON attempt_verifier_db.* TO 'attempt_user'@'localhost';

-- Reload the privilege tables to make the new user and grants effective immediately.
FLUSH PRIVILEGES;


-- 2. SCHEMA DEFINITION: Create the 'attempts' Table

-- Switch context to the new database
USE attempt_verifier_db;

-- Create the core 'attempts' table to store verification records.
CREATE TABLE attempts (
    -- Primary Key, auto-generated by the database
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- Runner metadata
    runner_id VARCHAR(100) NOT NULL,
    timestamp DATETIME NOT NULL,

    -- Computed metrics
    distance_km DOUBLE NOT NULL,
    elevation_gain_m DOUBLE NOT NULL,
    difficulty_score DOUBLE NOT NULL,

    -- Verification outcome
    result VARCHAR(20) NOT NULL,        -- Stores VERIFIED, FLAGGED, or REJECTED
    message VARCHAR(255)                -- Optional diagnostic/explanation message
);

-- End of script